# Generated by Django 5.2.5 on 2025-08-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='투자상품')),
                ('description', models.TextField(verbose_name='상품설명')),
                ('create_at', models.TimeField(auto_now=True, verbose_name='생성일')),
            ],
        ),
    ]
